create table Member (
  MemberId integer PRIMARY key GENERATED BY default AS IDENTITY,
  FirstName varchar(60) not null,
  LastName varchar(60) not null,
  ContactEmail varchar(60)  null,
  ContactPhoneNumber varchar(20)  null,
  CreatedDate timestamptz NOT null default now()
) 


create table NFCCard (
  NFCCardId integer PRIMARY key GENERATED BY default AS IDENTITY,
  CardNumber varchar(60) not null,
  IsActive boolean not null,
  CreatedDate timestamptz NOT null default now()
) 


create table MemberNFCCardAssoc
(
  MemberId integer not null,
  NFCCardId integer not null
) 

create table AttendanceLog
(
AttendanceLog integer PRIMARY key GENERATED BY default AS IDENTITY,
NFCCardId integer not null,
LogDate timestamptz NOT null
)


INSERT INTO public.nfccard
(cardnumber, isactive, createddate)
VALUES('abc123', TRUE, now());


create view vw_Attendance as
select *, ROUND(cast(EXTRACT(EPOCH FROM (logoutTime - LoginTime))/60 as decimal), 2) AS AttendanceTime 
from
(
	select cast(logdate as date) LogDate, n.cardnumber, m.memberid, m.firstname, m.lastname,
	min(a.logdate) LoginTime, max(a.logdate) logoutTime
	from attendancelog a 
	join nfccard n on a.nfccardid = n.nfccardid 
	join membernfccardassoc m2 on m2.nfccardid = n.nfccardid 
	join "member" m on m.memberId = m2.memberid 
	group by cast(logdate as date), n.cardnumber, m.memberid, m.firstname, m.lastname
) x;

---- 

INSERT INTO public."member"
(firstname, lastname, contactemail, contactphonenumber, createddate)
VALUES('Sterling', 'Platt', 'sterlingdoesmc@gmail.com', '4043848385', now());


insert into public.attendancelog
select 1, 1, now();

insert into public.attendancelog
(nfccardid, logdate)
values( 1, now());


select * from "member" m ;
select * from nfccard n ;

insert into membernfccardassoc
select 1, 1;
